server:
  port: 8081
  tomcat:
    threads:
      max: 300

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/db_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    lettuce: # redis连接池配置
      pool:
        enabled: true
        max-active: 100
        max-idle: 20
        min-idle: 5

rocketmq:
  name-server: 192.168.3.19:9876
  producer:
    group: springboot-producer-group
    send-message-timeout: 30000 # 发送消息超时时间
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数
    max-message-size: 4194304 # 消息最大长度4M

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


